Arch:
  name: enet
  num_classes: 4
Dataset:
  augment: PILaugment
  metainfo:
    - getImage_GT
    - foldernames:
        - img
        - gt
  pin_memory: False
  root_dir: dataset/ACDC-all
  subfolders:
    - img
    - gt
  transform: segment_transform((256,256))
Trainer:
  max_epoch: 100
  save_dir: tmp/ACDC_meanteacher
  device: cuda:0
  axises: [1,2,3]
  metricname: metrics.csv

Lab_Dataloader:
  batch_size: 3
  drop_last: true
  num_workers: 3
  pin_memory: false
  shuffle: true
  batch_sampler: [PatientSampler,
                  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]
Lab_Partitions:
  num_models: 1
  partition_sets: 0.5
  partition_overlap: 1
Optim:
  lr: 0.0005
  name: Adam
Scheduler:
  gamma: 0.7
  milestones:
    - 10
    - 20
    - 30
    - 40
    - 50
    - 60
    - 70
    - 80
    - 90
  name: MultiStepLR
Unlab_Dataloader:
  batch_size: 3
  drop_last: true
  num_workers: 3
  pin_memory: false
  shuffle: true