Arch:
  name: deeplabenet
  num_classes: 19

Optim:
  name: Adam
  lr: 0.0005
  weight_decay: 0.0002

Scheduler:
  name: StepLR
  step_size: 100
  gamma: 0.1

Dataset:
  root_dir: dataset/Cityscapes
  image_size: (512, 1024)
  augmentations:
#    rotate: 10                                    #[rotate -d to d degrees]
#    rcrop: [384, 768]                                #[crop of size (h,w)]

Dataloader:
  pin_memory: False
  batch_size: 4
  num_workers: 16
  shuffle: True
  drop_last: True

Trainer:
  max_epoch: 300
  save_dir: tmp/cityscape
  device:  cuda:0
  metricname: metrics.csv

Loss:
  name: cross_entropy
  ignore_index: 255
  weight: [  3.3632, 14.0408,  4.9860, 39.2617, 36.5217, 32.8975, 46.2848,
             40.6888,  6.6957, 33.5658, 18.4602, 32.9788, 47.6773, 12.7070, 45.2075,
             45.7849, 45.8268, 48.4074, 42.7600]

StartTraining:
  save_train: False
  save_val: True
  augment_labeled_data: False
