Arch:
  name: unet
  num_classes: 4
  in_channels: 3

Optim:
  name: Adam
  lr: 0.0005

Scheduler:
  name: MultiStepLR
  milestones: [10,20,30,40,50,60,70,80,90]
  gamma: 0.7


Dataset:
  root_dir: dataset/CITYSCAPES
  subfolders: ['leftImg8bit','gtFine']
  transform: # segment_transform((256,256))
  augment: # PILaugment
  pin_memory: False
  image_size: (512, 1024)
  img_rows: 512
  img_cols: 1024
  augmentations:
    rsize: [512, 1024]
    hflip: 0.5
    rotate: 10
#    rcrop: [h, w]                                #[crop of size (h,w)]
#    rotate: d                                    #[rotate -d to d degrees]
#    scale: [h,w]                                 #[scale to size (h,w)]
#    ccrop: [h,w]                                 #[center crop of (h,w)]



Lab_Dataloader:
  pin_memory: False
  batch_size: 2
  num_workers: 2
  shuffle: True
  drop_last: True
  batch_sampler: # [PatientSampler,
                  #  {grp_regex: '(patient\d+_\d+)_\d+',shuffle: False}]
Unlab_Dataloader:
  pin_memory: False
  batch_size: 4
  num_workers: 4
  shuffle: True
  drop_last: True


Trainer:
  max_epoch: 100
  save_dir: tmp/cotraining
  device: cuda
  axises: [1,2,3]
  metricname: metrics.csv
  lambda_cot_max: 1
  lambda_adv_max: 0.05
  ramp_up_mult: -5
  epoch_max_ramp: 80

Loss:
  name: cross_entropy
  weight: [1, 1, 1, 1]

StartTraining:
  train_jsd: False
  train_adv: False
  save_train: True
  save_val: False